project:
  type: website
  resources:
    - keybase.txt
    - cv.pdf
website:
  title: "Maureen Mugo"
  description: "Tech Blog"
  site-url: https://maureenmugo.dev/
  favicon: favicon.ico
  twitter-card: true
  open-graph: true
  reader-mode: true
  repo-url: https://github.com/maureen-mugo/maureenmugo.dev
  repo-actions: [edit, issue]
  navbar:
    search: true
    background: dark
    foreground: light
    left:
      - href: notes.qmd
        text: Notes
      - href: blog.qmd
        text: Blog
      - href: projects.qmd
        text: Projects
    right:
      - icon: github
        href: https://github.com/maureen-mugo
      - icon: twitter
        href: https://twitter.com/Maureen__Mugo
      - icon: rss
        href: index.xml
  page-footer:
    background: dark
    left: "© Copyright 2023 Maureen Mugo"
    center:
      - icon: github
        href: https://github.com/maureen-mugo
      - icon: twitter
        href: https://twitter.com/Maureen__Mugo
      - icon: linkedin
        href: https://www.linkedin.com/in/maureen-mugo-6a215a178/
format:
  html:
    theme:
      light: lumen
      dark: dark
    css: styles.css



